name: Build and Push to ACR
on:
    workflow_run:
      workflows: ["Node.js TEST & BUILD"]
      types:
        - completed
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: docker build -t my-project-backend .
      - run: docker login -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}} ${{secrets.ACR_URL}}
      - run: docker tag my-project-backend registrymyproject.azurecr.io/my-project-backend
      - run: docker push registrymyproject.azurecr.io/my-project-backend
